name: Build

on:
  push:
    branches: [ master ]
    tags:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.6.0
      with:
        version: v1.53
    - name: golint
      uses: Jerome1337/golint-action@v1.0.3
    - name: Test
      run: go test ./...
